# Generated by Django 4.1.3 on 2022-11-28 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transicao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Débito", "Debito"),
                            ("Boleto", "Boleto"),
                            ("Financiamento", "Fianciamento"),
                            ("Crédito", "Credito"),
                            ("Recebimento Empréstimo", "Rec Emprestimo"),
                            ("Vendas", "Vendas"),
                            ("Recebimento TED", "Rec Ted"),
                            ("Recebimento DOC", "Rec Doc"),
                            ("Aluguel", "Aluguel"),
                        ],
                        max_length=25,
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.FloatField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=13)),
                ("hora", models.TimeField()),
                ("dono", models.CharField(max_length=15)),
                ("loja", models.CharField(max_length=20)),
            ],
        ),
    ]
